require 'erb'
require './download_artifacts'
require './reporter'

desc "Generate report"
task :report do
  @reporter = Elastic::Reporter.new
  template = ERB.new(File.read('./template.erb'), trim_mode = true)
  File.write('../apis_report.md', template.result(binding))
end

desc "Download artifacts"
task :download do
  Elastic::download_artifacts(ENV['STACK_VERSION'] || '8.13.0-SNAPSHOT')
end
