# Licensed to Elasticsearch B.V. under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Elasticsearch B.V. licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

require 'erb'
require './download_artifacts'
require './reporter'

desc 'Generate report'
task :report do
  @reporter = Elastic::Reporter.new
  template = ERB.new(File.read('./template.erb'), trim_mode: '-')
  File.write('../apis_report.md', template.result(binding))
end

desc 'Download Elasticsearch Stack artifacts'
task :download_json do
  Elastic::download_json_spec
end

desc 'Download Elasticsearch Serverless artifacts'
task :download_spec do
  Elastic::download_es_specification
end

desc 'Download all artifacts'
task :download_all do
  Rake::Task['download_json'].invoke
  Rake::Task['download_spec'].invoke
end

desc 'Open an irb session preloaded with this library'
task :console do
  sh 'irb -r rubygems -I lib -r ./console.rb'
end
