require 'erb'
require './download_artifacts'
require './reporter'

desc 'Generate report'
task :report do
  @reporter = Elastic::Reporter.new
  template = ERB.new(File.read('./template.erb'), trim_mode: '-')
  File.write('../apis_report.md', template.result(binding))
end

desc 'Download Elasticsearch Stack artifacts'
task :download_json do
  version = ENV['STACK_VERSION'] || read_version_from_github
  Elastic::download_json_spec(version)
end

def read_version_from_github
  yml = File.read(File.expand_path('../.github/workflows/report.yml', __dir__))
  regexp = /[0-9.]+(-SNAPSHOT)?/
  yml.split("\n").select { |l| l.match?('STACK_VERSION') }.first.strip.match(regexp)[0]
end

desc 'Download Elasticsearch Serverless artifacts'
task :download_spec do
  Elastic::download_es_specification
end

desc 'Download all artifacts'
task :download_all do
  Rake::Task['download_json'].invoke
  Rake::Task['download_spec'].invoke
end
